import type { Metadata } from "next";
import { Poppins, Lobster } from 'next/font/google'
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
})

const lobster = Lobster({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lobster",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.variable} ${lobster.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
